Fstop1 = 1500;
Fpass1 = 2000;
Fpass2 = 3000;
Fstop2 = 3500;
Astop1 = 70;
Apass  = 3;
Astop2 = 70;
Fs = 8192;
d9 = designfilt("bandpassiir", ...
    StopbandFrequency1=Fstop1, ...
    PassbandFrequency1=Fpass1, ...
    PassbandFrequency2=Fpass2, ...
    StopbandFrequency2=Fstop2, ...
    StopbandAttenuation1=Astop1, ...
    PassbandRipple=Apass, ...
    StopbandAttenuation2=Astop2, ...
    DesignMethod="butter", ...
    SampleRate=Fs);
filterAnalyzer(d9)
filtord(d9)